In [1]:
import pandas as pd

## Кодирование признаков

In [2]:
df = pd.read_csv('C:/telco_customer_churn/clean_data.csv')
df.head().T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No,No,No,No,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

Бинарные признаки

In [3]:
bin_cols = ['gender', 'Partner', 'Dependents', 'PhoneService', 
            'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 
            'DeviceProtection', 'TechSupport', 'StreamingTV', 
            'StreamingMovies', 'PaperlessBilling', 'Churn']

gender_map = {'Male': 1, 'Female': 0}
others_map = {'Yes': 1, 'No': 0}

for col in bin_cols:
    if col == 'gender':
        df[col] = df[col].map(gender_map)
    else:
        df[col] = df[col].map(others_map)

In [4]:
df.head(3).T

                                 0             1               2
Unnamed: 0                       0             1               2
customerID              7590-VHVEG    5575-GNVDE      3668-QPYBK
gender                           0             1               1
SeniorCitizen                    0             0               0
Partner                          1             0               0
Dependents                       0             0               0
tenure                           1            34               2
PhoneService                     0             1               1
MultipleLines                    0             0               0
InternetService                DSL           DSL             DSL
OnlineSecurity                   0             1               1
OnlineBackup                     1             0               1
DeviceProtection                 0             1               0
TechSupport                      0             0               0
StreamingTV                      0             0               0
StreamingMovies                  0             0               0
Contract            Month-to-month      One year  Month-to-month
PaperlessBilling                 1             0               1
PaymentMethod     Electronic check  Mailed check    Mailed check
MonthlyCharges               29.85         56.95           53.85
TotalCharges                 29.85        1889.5          108.15
Churn                            0             0               1

One Hot кодирование

In [5]:
df['InternetService'].unique()

<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

In [6]:
df['Contract'].unique()

<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

In [7]:
df['PaymentMethod'].unique()

<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [8]:
one_hot_features = ['InternetService', 'Contract', 'PaymentMethod']

df = pd.get_dummies(df, columns=one_hot_features, dtype='int')

In [10]:
df.head().T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,0,1,1,1,0
SeniorCitizen,0,0,0,0,0
Partner,1,0,0,0,0
Dependents,0,0,0,0,0
tenure,1,34,2,45,2
PhoneService,0,1,1,0,1
MultipleLines,0,0,0,0,0
OnlineSecurity,0,1,1,1,0
OnlineBackup,1,0,1,0,0
DeviceProtection,0,1,0,1,0
TechSupport,0,0,0,1,0
StreamingTV,0,0,0,0,0
StreamingMovies,0,0,0,0,0
PaperlessBilling,1,0,1,0,1
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,0,0,1,0,1
InternetService_DSL,1,1,1,1,0
InternetService_Fiber optic,0,0,0,0,1
InternetService_No,0,0,0,0,0
Contract_Month-to-month,1,0,1,0,1
Contract_One year,0,1,0,1,0
Contract_Two year,0,0,0,0,0
PaymentMethod_Bank transfer (automatic),0,0,0,1,0
PaymentMethod_Credit card (automatic),0,0,0,0,0
PaymentMethod_Electronic check,1,0,0,0,1
PaymentMethod_Mailed check,0,1,1,0,0

In [11]:
df.columns

Index(['Unnamed: 0', 'customerID', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'Churn', 'InternetService_DSL',
       'InternetService_Fiber optic', 'InternetService_No',
       'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [12]:
need_columns = ['gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'Churn', 'InternetService_DSL',
       'InternetService_Fiber optic', 'InternetService_No',
       'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']